@extends('docs.layout')
@section('content')
<section class="border-b border-slate-200 dark:border-slate-800"><div class="mx-auto max-w-[1400px] px-4 py-20 sm:px-6 lg:px-8 lg:py-28"><div class="max-w-3xl">
<span class="inline-flex rounded-full border border-slate-200 bg-slate-50 px-3 py-1 font-mono text-xs text-slate-500 dark:border-slate-800 dark:bg-slate-900">Laravel Telegram Bot Router · Laravel 10–13 · PHP 8.1+</span>
<h1 class="mt-6 text-[42px] font-bold leading-[1.1] tracking-tight sm:text-[56px]">Route Telegram updates<br><span class="text-red-600 dark:text-red-400">like HTTP requests.</span></h1>
<p class="mt-6 text-lg leading-8 text-slate-500">A Laravel-native router for Telegram bots. Define commands, messages and callbacks in a dedicated bot route file and send them to controllers with middleware, parameters, keyboards, queues and a response API.</p>
<div class="mt-9 flex flex-wrap gap-3"><a href="{{ route('docs.show',['path'=>'getting-started/quick-start']) }}" class="rounded-md bg-red-600 px-5 py-2.5 text-sm font-medium text-white hover:opacity-90">Get Started →</a><a href="{{ route('docs.show',['path'=>'getting-started/introduction']) }}" class="rounded-md border border-slate-200 px-5 py-2.5 text-sm font-medium hover:bg-slate-50 dark:border-slate-800 dark:hover:bg-slate-900">Documentation</a><a href="https://github.com/ReyhanTeam/laravel-telegram-bot-router" target="_blank" class="rounded-md border border-slate-200 px-5 py-2.5 text-sm font-medium hover:bg-slate-50 dark:border-slate-800 dark:hover:bg-slate-900">GitHub</a></div>
</div></div></section>
<section class="border-b border-slate-200 bg-slate-50/60 dark:border-slate-800 dark:bg-slate-900/30"><div class="mx-auto max-w-[1400px] px-4 py-16 sm:px-6 lg:px-8"><h2 class="text-2xl font-semibold">Architecture</h2><p class="mt-2 max-w-2xl text-[15px] leading-7 text-slate-500">Every update follows the same route pipeline, whether it arrives by webhook or polling.</p><div class="mt-8 grid gap-3 md:grid-cols-5">@foreach(['Webhook / Polling','Update Manager','Telegram Router','Middleware','Controller → Response'] as $i=>$step)<div class="rounded-lg border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-950"><div class="text-xs text-slate-500">{{ $i+1 }}</div><div class="mt-2 font-medium">{{ $step }}</div></div>@endforeach</div></div></section>
<section class="border-b border-slate-200 dark:border-slate-800"><div class="mx-auto max-w-[1400px] px-4 py-16 sm:px-6 lg:px-8"><h2 class="text-2xl font-semibold">Everything a production bot needs</h2><div class="mt-8 grid gap-px overflow-hidden rounded-xl border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-3 dark:border-slate-800 dark:bg-slate-800">@foreach([['Telegram Routing','Commands, messages and callbacks.'],['Webhook','Dedicated secured webhook route.'],['Polling','Long polling for local development.'],['Controllers','Normal Laravel controller methods.'],['Middleware','Authorization and cross-cutting logic.'],['Keyboards','Reply and inline keyboard builders.'],['Queue','Background processing for slow updates.'],['Rate Limiting','Per-user, per-chat and per-command limits.'],['Response API','Fluent Telegram responses.'],['Testing','Fake API calls and assertions.']] as [$title,$text])<div class="bg-white p-5 dark:bg-slate-950"><h3 class="font-semibold">{{ $title }}</h3><p class="mt-1.5 text-sm leading-6 text-slate-500">{{ $text }}</p></div>@endforeach</div></div></section>
<section><div class="mx-auto grid max-w-[1400px] gap-10 px-4 py-16 sm:px-6 lg:grid-cols-2 lg:px-8"><div><h2 class="text-2xl font-semibold">Quick start</h2><p class="mt-3 text-[15px] leading-7 text-slate-500">Install the package, publish <code>routes/bot.php</code>, then declare Telegram routes separately from Laravel HTTP routes.</p><a href="{{ route('docs.show',['path'=>'getting-started/installation']) }}" class="mt-7 inline-flex text-sm font-medium text-red-600 hover:underline dark:text-red-400">Read the installation guide →</a></div><div class="overflow-hidden rounded-lg border border-slate-200 bg-slate-50 dark:border-slate-800 dark:bg-slate-900"><pre class="overflow-x-auto p-5 text-[13px] leading-6"><code>use ReyhanTeam\TelegramBotRouter\Facades\TelegramRoute;

TelegramRoute::onCommand('start', [StartController::class, 'start']);
TelegramRoute::onCommand('help', [HelpController::class, 'help']);
TelegramRoute::onCallback('order:{id}:cancel', [OrderController::class, 'cancel']);</code></pre></div></div></section>
@endsection
